routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

//admin routes
Route::view("/admin/login", "layouts.login");
Route::view("/admin/{path?}", "layouts.admin")->where("path", "[a-zA-Z@0-9/?=-]+");

//Important Routes
Auth::routes(['verify' => true]);

//Website Routes
Route::get("/", "HomeController@index")->name('home');
Route::get('/search', 'HomeController@search')->name('search');
Route::get('/pro-search', 'HomeController@proSearch')->name('pro_search');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/contact', 'ContactController@getContact')->name('contactView');
Route::post('/contact', 'ContactController@saveContact')->name('contact');;
Route::post('/lang', 'HomeController@lang')->name('lang');

//Post Routes
Route::get('/post/{slug}', 'ArticleController@show')->name('post');

//Category Routes
Route::get('/categories', 'CategoryController@index')->name('categories');
Route::get('/category/{slug}', 'CategoryController@getArticlesCategory')->name('category');


//User Routes
Route::get("/profile", "UserController@show")->name('show_profile');
Route::put("/profile", "UserController@update")->name('update_profile');
Route::get("/favorite", "UserController@showFavorite")->name('show_favorite');
Route::post("/favorite", "UserController@addFavorite")->name('add_favorite');
Route::delete("/favorite", "UserController@deleteFavorite")->name('delete_favorite');
Route::get("/transaction", "UserController@showTransactions")->name('my_transactions');


//Comment Routes
Route::post("/comment", "UserController@addComment")->name('add_comment');


//Payment Routes
Route::get('/payment/{slug}/request', 'Payment\ZarinPalController@request')->name('request_payment');
Route::any('/payment/verify', 'Payment\ZarinPalController@verify')->name('verify_payment');
Route::get('/post/{slug}/pdf','ArticleController@downloadPDF')->name('post.pdf');
Route::get('/payment/result', 'Payment\ZarinPalController@showResult')->name('payment_result');


Route::get('/test', function (){
    return view('vendor.shetabitPayment.redirectForm');
});

app/Article.php
<?php

namespace App;

use Carbon\Carbon;
use Hekmatinasser\Verta\Verta;
use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class Article extends Model
{
    use Sluggable;

    const FREE = 1;
    const PREMIUM = 0;

    protected $guarded = ["id"];

    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function userFavorites()
    {
        return $this->belongsToMany(User::class, 'article_favorite');
    }

    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function getCreatedAtAttribute($data)
    {
        return $this->convertDate($data);
    }

    public function getUpdatedAtAttribute($data)
    {
        return $this->convertDate($data);
    }

    public function getCreatedAtEnAttribute()
    {
        return Carbon::create($this->attributes["created_at"])->format("Y M d");
    }

    public function getUpdatedAtEnAttribute()
    {
        return Carbon::create($this->attributes["updated_at"])->format("Y M d");
    }

    public function getStatusFaAttribute($data)
    {
        return $this->attributes["status"] ? "منتشر شده" : "منتشر نشده";
    }

    private function convertDate($date)
    {
        $jalali = new Verta($date);
        return $jalali->format("d %B Y");
    }

    public function transactions()
    {
        return $this->hasMany(Transaction::class);
    }

    public function isFree()
    {
        return $this->is_free === static::FREE;
    }

    public function isPaid()
    {
        if (!auth()->check()) {
            return false;
        }
        return !! $this->transactions()->where('user_id',auth()->id())->where('status',Transaction::SUCCESS)->first();

    }
}

app/User.php
<?php

namespace App;

use Gravatar;
use Hekmatinasser\Verta\Verta;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Tymon\JWTAuth\Contracts\JWTSubject;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable implements MustVerifyEmail, JWTSubject
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = ["id"];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Get the identifier that will be stored in the subject claim of the JWT.
     *
     * @return mixed
     */
    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }

    public function articles()
    {
        return $this->hasMany(Article::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function favorites()
    {
        return $this->belongsToMany(Article::class, 'article_favorite');
    }

    public function getCreatedAtAttribute($data)
    {
        return $this->convertDate($data);
    }

    public function getUpdatedAtAttribute($data)
    {
        return $this->convertDate($data);
    }

    public function getRoleFaAttribute($data)
    {
        return $this->attributes["role"] === 1 ? "ادمین" : "کاربر";
    }

    public function getStatusFaAttribute($data)
    {
        return $this->attributes["status"] ? "فعال" : "غیر فعال";
    }

    // public function getAvatarAttribute($data)
    // {
    //     $avatar = $this->attributes["avatar"];
    //     if ($avatar == "/images/male.png" || $avatar == "/images/female.png" || $avatar == "/images/other.png") {
    //         if (Gravatar::exists($this->attributes["email"])) {
    //             $avatar = Gravatar::get($this->attributes["email"]);
    //         }
    //     }
    //     return $avatar;
    // }

    private function convertDate($date)
    {
        $jalali = new Verta($date);
        return $jalali->format("d %B Y");
    }

    public function transactions()
    {
        return $this->hasMany(Transaction::class);
    }

}

resources/views/web/about.blade.php
@extends('web.layouts.master')

@section('title', 'Tiny Blog - About Page')

@section('styles')
    <style>

        .about_row {
            background-color: #100f2c !important;
            border-radius: 8px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            direction: {{app()->getLocale() === 'en' ? 'ltr':'rtl'}}   !important;
        }

        .about_row * {
            color: #fff !important;
        }

        .about_row hr {
            background: #fff;
        }

        .darkmode--activated .about_row {
            background-color: #ccc !important;
        }

        .darkmode--activated .about_row {
            color: black !important;
        }

        .darkmode--activated .about_row * {
            color: #fff !important;
        }


    </style>
@endsection


@section('header')
    <header class="header">
        @include('web.layouts.header')
        @include('web.layouts.intro')
    </header>
@endsection

@section('content')

    <section>
        <div class="container-fluid white">
            <hr class="mb-5 mt-0">
            <div class="container">

                <!-- Section: Blog v.3 -->
                <section class="mt-5 py-5 text-center text-lg-left">

                    <!-- Grid row -->
                    <div class="row my-xl-5 py-xl-4  about_row">

                        <!-- Grid column -->
                        <div class="col-sm-12 col-md-5 col-xl-5 m-4 about_main">

                            <!-- Image -->
                            <div class="view overlay">
                                <img style="border-radius: 5px" src="/images/about_us.png" class="img-fluid z-depth-1"
                                     alt="">
                                <div class="mask rgba-white-slight"></div>
                            </div>
                            <!-- Image -->

                        </div>
                        <!-- Grid column -->

                        <!-- Grid column -->
                        <div class="col-sm-12 col-md-6 col-xl-6">

                            <h3 class="pb-2 font-weight-bold" style="text-align: {{app()->getLocale() === 'en' ? 'left':'right'}};">
                                <strong>@lang('site.about.about_us')</strong>
                            </h3>
                            <hr>

                            <p class=" mt-4 text-justify">@lang('site.about.about_us_text')</p>
                        </div>
                        <!-- Grid column -->

                    </div>
                    <!-- Grid row -->

                </section>
                <!-- Section: Blog v.3 -->

            </div>

        </div>

    </section>

@endsection

@section('footer')
    @include('web.layouts.footer')
@endsection

resources/views/web/categories.blade.php
@extends('web.layouts.master')

@section('title', 'Tiny Blog - Categories Page')

@section('header')
    <header class="header">
        @include('web.layouts.header')
        @include('web.layouts.intro')
    </header>
@endsection

@section('content')

    <section>
        <div class="container-fluid">

            <div class="container mt-5 pt-3">

                @if (app()->getLocale()=='en')

                    <h1 class="title font-weight-bold text-left"
                        style="font-size: xxx-large;">@lang('site.categories.categories_list')</h1>

                @elseif(app()->getLocale()=='fa')
                    <h1 class="title font-weight-bold text-left"
                        style="font-size:xxx-large;">@lang('site.categories.categories_list')</h1>

                @endif
                <hr class="my-5">
                <div class="row mt-4 pt-3">
                    <div class="col-lg-9 col-12 mt-1">
                        <div class="row">

                            <!-- Card -->
                            @foreach($categories as $category)
                                <div class="col-md-3 col-sm-6 col-12 mb-4">
                                    <a href="{{route('category',[mb_strtolower($category->slug,'UTF-8')])}}">
                                        <div class="card card-image"
                                             style="background-image: url(./images/photo8.jpg); border-radius: 30px;">

                                            <!-- Content -->
                                            <div
                                                class="text-white text-center d-flex align-items-center rgba-black-light py-5 px-4"
                                                style="border-radius: 30px;">
                                                <div>
                                                    <h3 class="card-title pt-2">
                                                        @if (app()->getLocale()=='en')
                                                            <strong class="p_darkmode_handler">{{ucwords($category->name)}}</strong>
                                                        @elseif(app()->getLocale()=='fa')
                                                            <strong class="p_darkmode_handler">{{$category->name_fa}}</strong>
                                                        @endif
                                                    </h3>
                                                </div>
                                            </div>

                                        </div>

                                    </a>
                                </div>
                        @endforeach
                        <!-- Card -->

                        </div>
                    </div>

                    <div class="col-lg-3 col-12 mt-1 wow fadeIn" data-wow-delay="0.2s">
                        @include('web.layouts.sidebar')
                    </div>

                </div>
            </div>
        </div>
    </section>



@endsection

@section('footer')
    @include('web.layouts.footer')
@endsection

resources/views/web/category.blade.php
@extends('web.layouts.master')

@section('title', 'Tiny Blog - Category Page')

@section('styles')
    <style>
        .darkmode--activated .title{
            color:#000 !important;
        }


    </style>
@endsection

@section('header')
    <header class="header">
        @include('web.layouts.header')
        @include('web.layouts.intro')
    </header>
@endsection


@section('content')
    <!-- Blog section -->
    <section>

        <div class="container mt-5 pt-3">

            <!-- Main listing -->
            <div class=" mt-1">


                    @if ($category)
                        @if (app()->getLocale()=='en')

                            <p class="title text-left" style="font-size: x-large;">
                             @lang('site.category.category_list'):
                            {{ucfirst($category->name)}}
                            </p>
                        @elseif(app()->getLocale()=='fa')
                            <p class="title text-right" style="font-size: x-large;">
                                @lang('site.category.category_list'):
                                {{ucfirst($category->name_fa)}}
                            </p>
                        @endif
                    @else
                        @lang('site.category.category_not_found')
                    @endif



                <hr class="my-5">



            </div>

            <!-- Blog -->
            <div class="row mt-5 pt-3">




                @include('web.layouts.post')
                <!-- Main listing -->

                <!-- Sidebar -->
                <div class="col-lg-3 col-12 mt-1">
                    @include('web.layouts.sidebar')
                </div>
                <!-- Sidebar -->
            </div>
            <!-- Blog -->

        </div>
        <!-- Main listing -->


    </section>
    <!-- Blog section -->

@endsection

@section('footer')
    @include('web.layouts.footer')
@endsection

resources/views/web/index.blade.php
@extends('web.layouts.master')

@section('title', 'Tiny Blog - Home Page')

@section('header')
    <header class="header">
    @include('web.layouts.header')
    @include('web.layouts.intro')
    </header>
@endsection


@section('content')
    <!-- Blog section -->
    <section>

        <div class="container mt-5 pt-3">

            <!-- Blog -->
            <div class="row mt-5 pt-3">

                @include('web.layouts.post')

                <!-- Sidebar -->
                <div class="col-lg-3 col-12 mt-1">
                    @include('web.layouts.sidebar')
                </div>
                <!-- Sidebar -->
            </div>
            <!-- Blog -->

        </div>
        <!-- Main listing -->


    </section>
    <!-- Blog section -->

@endsection

@section('footer')
    @include('web.layouts.footer')
@endsection

resources/views/web/transaction.blade.php
@extends('web.layouts.master')

@section('title', 'Tiny Blog - Transaction Page')

@section('header')
    <header class="header">
        @include('web.layouts.header')
        @include('web.layouts.intro')
    </header>
@endsection


@section('content')
    <!-- Blog section -->
    <section>

        <div class="container mt-5 pt-3">

            @if (app()->getLocale()=='en')

                <h1 class="title text-left"
                    style="font-size: x-large;">@lang('site.transaction.transaction_list')</h1>

            @elseif(app()->getLocale()=='fa')
                <h1 class="title text-right"
                    style="font-size: x-large;">@lang('site.transaction.transaction_list')</h1>

            @endif


            <hr class="my-5 hr_darkmode_handler">

            <!-- Blog -->
            <div class="row mt-5 pt-3">

                <div class="col-lg-9 col-12 mt-1">


                    @if (app()->getLocale()=='en')

                        <table class="table table-striped table-hover table-dark text-center"
                               style="direction: ltr; font-family: Helvetica, Arial, sans-serif">

                            @elseif(app()->getLocale()=='fa')

                                <table class="table table-striped table-hover table-dark text-center"
                                       style="direction: rtl">

                                    @endif

                                    <thead class="bg-default">
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">@lang('site.transaction.article_name')</th>
                                        <th scope="col">@lang('site.transaction.amount')</th>
                                        <th scope="col">@lang('site.transaction.status')</th>
                                        <th scope="col">@lang('site.transaction.transaction_id')</th>
                                        <th scope="col">@lang('site.transaction.ref_id')</th>
                                        <th scope="col">@lang('site.transaction.gate')</th>
                                        <th scope="col">@lang('site.transaction.date')</th>
                                    </tr>
                                    </thead>
                                    <tbody>


                                    @if (isset($transactions))

                                        @foreach($transactions as $transaction)




                                            <tr>
                                                <th scope="row">{{(($transactions->currentPage()-1)*$transactions->perpage())+$loop->index+1}}</th>
                                                <td><a class="text-primary"
                                                       href="{{route('post',[mb_strtolower(\App\Article::where('id',$transaction->article_id)->first()->slug,'UTF-8')])}}">@lang('site.transaction.article_show_link')</a>
                                                </td>
                                                <td>{{number_format($transaction->amount)}}</td>
                                                @if ($transaction->status == 1)
                                                    <td class="bg-success">@lang('site.transaction.ok')</td>
                                                @elseif($transaction->status == 0)
                                                    <td class="bg-danger">@lang('site.transaction.nok')</td>
                                                @endif
                                                <td>{{ltrim(ltrim($transaction->transaction_id,"A"),"0")}}</td>
                                                <td>{{(is_null($transaction->ref_id))?'-':$transaction->ref_id}}</td>
                                                <td>{{(is_null($transaction->driver))?'-':$transaction->driver}}</td>
                                                @if (app()->getLocale()=='en')

                                                    <td>{{$transaction->created_at_en}}</td>

                                                @elseif(app()->getLocale()=='fa')

                                                    <td>{{$transaction->created_at}}</td>

                                                @endif
                                            </tr>
                                        @endforeach


                                    @endif


                                    </tbody>
                                </table>

                            @if (isset($transactions))
                                <!-- Pagination dark grey -->
                                    <nav class="mb-5 pb-2 justify-content-center d-flex">
                                        {{$transactions->links()}}
                                    </nav>
                                    <!-- Pagination dark grey -->
                    @endif

                </div>

                <!-- Sidebar -->
                <div class="col-lg-3 col-12 mt-1">
                    @include('web.layouts.sidebar')
                </div>
                <!-- Sidebar -->
            </div>
            <!-- Blog -->

        </div>
        <!-- Main listing -->


    </section>
    <!-- Blog section -->

@endsection



@section('footer')
    @include('web.layouts.footer')
@endsection

resources/views/web/verify-payment.blade.php
@extends('web.layouts.master')


@section('title', 'Tiny Blog - Payment Result')

@section('styles')

    <style>
        /*        @import url('https://fonts.googleapis.com/css?family=Montserrat:400,800');*/

        * {
            box-sizing: border-box;
        }

        body {
            background: #f6f5f7;
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            height: 100vh;
            margin: -20px 0 50px;
        }


        h1 {
            font-weight: bold;
            margin: 0;
        }

        h2 {
            text-align: center;
        }

        p {
            font-size: 14px;
            font-weight: 100;
            line-height: 20px;
            letter-spacing: 0.5px;
            margin: 20px 0 30px;
        }

        span {
            font-size: 12px;
        }

        a {
            color: #333;
            font-size: 14px;
            text-decoration: none;
            margin: 15px 0;
        }

        button {
            border-radius: 20px;
            border: 1px solid #FF4B2B;
            background-color: #FF4B2B;
            color: #FFFFFF;
            font-size: 12px;
            font-weight: bold;
            padding: 12px 45px;
            letter-spacing: 1px;
            text-transform: uppercase;
            transition: transform 80ms ease-in;
        }

        button:active {
            transform: scale(0.95);
        }

        button:focus {
            outline: none;
        }

        button.ghost {
            background-color: transparent;
            border-color: #FFFFFF;
        }

        input {
            background-color: #eee;
            border: none;
            padding: 12px 15px;
            margin: 8px 0;
            width: 100%;
        }

        .container {
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.5) !important;
            position: relative;
            overflow: hidden;
            width: 768px;
            max-width: 100%;
            min-height: 350px;
            padding: 0px !important;
            transition: all 0.3s ease-in-out;
        }

        .darkmode--activated .container:hover {
            transform: scale(1.01);
            z-index: 2;
        }

        .container:hover {

            box-shadow: 0 14px 28px rgba(0, 0, 0, 0.25) !important;
            transform: scale(1.01);
            z-index: 2;
        }

        .content {
            left: 0;
            width: 50%;
            z-index: 2;
        }

        .sidebar-container {
            position: absolute;
            top: 0;
            right: -50%;
            width: 50%;
            height: 100%;
            z-index: 100;
            padding: 0px !important;
        }

        .sidebar {
            background: #FF416C;
            background: -webkit-linear-gradient(to right, #FF4B2B, #FF416C);
            background: linear-gradient(to right, #FF4B2B, #FF416C);
            background-repeat: no-repeat;
            background-size: cover;
            background-position: 0 0;
            color: #FFFFFF;
            position: relative;
            left: -100%;
            height: 100%;
            width: 200%;
        }

        .sidebar-panel {
            position: absolute;
            display: flex;
            align-items: center;
            justify-content: center;
            flex-direction: column;
            padding: 0 40px;
            text-align: center;
            top: 0;
            height: 100%;
            width: 50%;
        }

        .darkmode--activated span {
            color: black !important;
            background-color: #FFFFFF !important;
        }

        .darkmode--activated p {
            color: white !important;
        }

    </style>

@endsection



@section('content')

    <div class="container" id="container">
        <div class="row">
            <div class="col-lg-6 form-container content">

                @if(isset($transaction))
                    {{--status OK--}}
                    <section style="direction: rtl">
                        <figure class="title text-center pt-3">
                            <h3>جزئیات تراکنش</h3>
                        </figure>

                        <figure class="text-center pt-3  " style="display: flex !important; justify-content: center;">
                            <ul class="list-group list-group-flush p-0">

                                <li class="list-group-item">
                                    <label>نام محصول:</label>
                                    <a class="text-primary"
                                       href="{{route('post',[mb_strtolower(\App\Article::where('id',$transaction->article_id)->first()->slug,'UTF-8')])}}">@lang('site.transaction.article_show_link')</a>
                                </li>
                                <li class="list-group-item">
                                    <label>قیمت محصول (تومان):</label>
                                    {{number_format($transaction->amount)}}
                                </li>
                                @if ($transaction->status == 1)
                                    <li class="list-group-item text-success">
                                        <label>وضعیت تراکنش:</label>
                                        @lang('site.transaction.ok')
                                    </li>
                                @elseif($transaction->status == 0)
                                    <li class="list-group-item text-danger">
                                        <label>وضعیت تراکنش:</label>
                                        @lang('site.transaction.nok')
                                    </li>
                                @endif
                                <li class="list-group-item">
                                    <label>شناسه تراکنش:</label>
                                    {{ltrim(ltrim($transaction->transaction_id,"A"),"0")}}
                                </li>
                                <li class="list-group-item">
                                    <label>شناسه پرداخت:</label>
                                    {{(is_null($transaction->ref_id))?'-':$transaction->ref_id}}
                                </li>
                                <li class="list-group-item">
                                    <label>درگاه پرداخت:</label>
                                    {{(is_null($transaction->driver))?'-':$transaction->driver}}
                                </li>
                                @if (app()->getLocale()=='en')

                                    <li class="list-group-item">
                                        <label>تاریخ پرداخت:</label>
                                        {{$transaction->created_at_en}}
                                    </li>

                                @elseif(app()->getLocale()=='fa')

                                    <li class="list-group-item">
                                        <label>تاریخ پرداخت:</label>
                                        {{$transaction->created_at}}
                                    </li>

                                @endif
                            </ul>
                        </figure>

                    </section>

                @endif

            </div>

            @if($transaction->status == 1)
                <div class="col-lg-6 sidebar-container">
                    <div class="sidebar"
                         style="background: #009efd;background: -webkit-linear-gradient(180deg, #2af598 0%, #009efd 100%);background: linear-gradient(180deg, #2af598 0%, #009efd 100%);">
                        <div class="sidebar-panel sidebar-left pt-5 ">

                            <h1 class="mb-5">تاینی بلاگ</h1>
                            <h3>تراکنش موفق</h3>
                            <div class="fa-7x mb-3">
                                <i class="far fa-check-circle"></i>
                            </div>
                            <figure class="text-center pt-3">
                                <form action="{{route('home')}}"
                                      method="get">
                                    @csrf
                                <button class="btn btn-rounded waves-effect waves-light"  style="background-color: #2AF598FF; font-weight: bold !important; font-size: medium !important;" type="submit">بازگشت به سایت</button>
                                </form>
                            </figure>

                        </div>
                    </div>
                </div>
            @elseif($transaction->status == 0)
                <div class="col-lg-6 sidebar-container">

                    <div class="sidebar" style="background: #FF416C;background: -webkit-linear-gradient(to right, #FF4B2B, #FF416C);background: linear-gradient(to right, #FF4B2B, #FF416C);">

                    <div class="sidebar-panel sidebar-left  pt-5">

                            <h1 class="mb-5">تاینی بلاگ</h1>
                            <h3>تراکنش ناموفق</h3>

                            <div class="fa-7x mb-3">
                                <i class="far fa-times-circle"></i>
                                <h5 style="direction: rtl">{{$exception}}</h5>
                            </div>
                            <figure class="text-center pt-3">
                                <form action="{{route('home')}}"
                                      method="get">
                                @csrf
                                <button class="btn btn-rounded waves-effect waves-light"  style="background-color: #2AF598FF; font-weight: bold !important; font-size: medium !important;" type="submit">بازگشت به سایت</button>
                                </form>
                            </figure>

                        </div>
                    </div>
                </div>
            @endif
        </div>

    </div>

@endsection